sudo: required
services:
  - docker

os:
  - linux
  - osx

language:
  - cpp

env:
  global:
    # The next declration is the encrypted COVERITY_SCAN_TOKEN,
    # created via the "travis encrypt" command using the project repo's public key
    - secure: "YwdYHh5U9EtSUTm+QHvdbKBfE3l3fJkg915xhzRju+3w9a1PHutBtEM5cHf6B3tz7MfS+n2daUUY4IzA76hv0tJBBStnU0M6bf9zct9SUx+a82cV/KlOLN0kYaBRysRojFa5hjUL5tzmWl3hgAMA4zgZKv/QvW7Ts/A1/RI651I="
    - COVERITY_SCAN_PROJECT_NAME='Unvanquished/Unvanquished'
    - COVERITY_SCAN_NOTIFICATION_EMAIL='vcelestialragev@gmail.com'
    - COVERITY_SCAN_BUILD_COMMAND_PREPEND='mkdir build; cd build; CXXFLAGS="-D__extern_always_inline=inline" cmake -G "Ninja" -DBUILD_GAME_NACL=0 -DCMAKE_BUILD_TYPE=Debug ..'
    - COVERITY_SCAN_BUILD_COMMAND='cmake --build . -- -j8'
    - COVERITY_SCAN_BRANCH_PATTERN='coverity_scan2'
  matrix:
    # engine
    - MODE=0
    # game
    - MODE=1
    # nacl
    - MODE=2

compiler:
  - clang
  - gcc

matrix:
  exclude:
    - env: MODE=2  # Don't build NaCl gamelogic with gcc
      compiler: gcc

install:
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo rm -rf /opt/python; fi  # Delete conflicting python
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get install software-properties-common; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo add-apt-repository ppa:george-edison55/cmake-3.x -y; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get -qq update; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get -qq install
    cmake ninja-build
    liblua5.2-dev
    libgeoip-dev
    libncursesw5-dev
    libsdl2-dev libglew-dev libfreetype6-dev
    libwebp-dev libjpeg8-dev libpng-dev
    libcurl4-gnutls-dev zlib1g-dev
    libopenal-dev libogg-dev libvorbis-dev libtheora-dev libxvidcore-dev libopusfile-dev libspeexdsp-dev
    nettle-dev libgmp-dev python-yaml python-jinja2; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew update; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew install ninja; fi
  - sudo pip install -r src/utils/cbse/requirements.txt

script:
  # coverity gcc
  - if [[ "${TRAVIS_JOB_NUMBER##*.}" == "2" ]]; then curl -s "https://scan.coverity.com/scripts/travisci_build_coverity_scan.sh" | bash || true ; fi
  - mkdir -p build
  - cd build
  - cmake --version
  - CXXFLAGS="-D__extern_always_inline=inline" cmake
    -DBUILD_CLIENT=$(($MODE == 0)) -DBUILD_TTY_CLIENT=$(($MODE == 0)) -DBUILD_SERVER=$(($MODE == 0))
    -DBUILD_CGAME=$(($MODE >= 1)) -DBUILD_SGAME=$(($MODE >= 1))
    -DBUILD_GAME_NATIVE_DLL=$(($MODE == 1)) -DBUILD_GAME_NATIVE_EXE=$(($MODE == 1))
    -DBUILD_GAME_NACL=$(($MODE == 2))
    -DUSE_WERROR=1 -DBE_VERBOSE=1 -G "Ninja" -DBUILD_GAME_NACL_NEXE=0 -DCMAKE_BUILD_TYPE=Debug ..
  - cmake --build . -- -j8

notifications:
  irc:
    - "irc.freenode.org#unvanquished-dev"
    - "irc.quakenet.org#unvanquished"
  on_success: change
  on_failure: always

branches:
  except:
    - /^cbse\/.*$/
    - debian
